config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :coins
  get '/coins/delete', to: 'coins#delete'
  get 'welcome/index'
  get 'welcome/conocenos'
  get 'welcome/aprende'
  get 'cp/jugar'
  post "cp/jugar"
  get 'cp/perfil'
  get 'cp/saldo'
  post 'cp/saldo'
  get 'cp/resultados'

  root 'welcome#index'
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role == "admin"
        can :manage, :all
    else
        can :read, Result.all
    end
  end


end

app/models/bet.rb
class Bet < ActiveRecord::Base
  belongs_to :user
  belongs_to :coin
end

app/models/coin.rb
class Coin < ActiveRecord::Base
	has_many :bets
	has_many :users, through: :bets

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :coin
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  before_save :set_monto_saldo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bets 



  private

  def set_monto_saldo

  	self.monto ||= 0
  	self.saldo ||= 0
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include LoadAndAuthorizeResource
  include CanCan::ControllerAdditions
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end

  protect_from_forgery with: :exception
  def hora
  	@foo = Time.now.strftime("%R")
  end



  

end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
	before_action :set_coin, except:[:new,:create,:index]
	
	def index

		#Va a ser el index de mi paginas de articulos
		#Article.all devuelve un objeto con el que puedo iterar y obtener cada uno
		#de mis articulos
		@arreglo_de_monedas = Coin.all
		authorize! :read, @arreglo_de_monedas

	end

	def show 

		#Va a ser la pagina de cada uno de mis articulos
		#puedo obtener mi articulo con Article.find para agregarle estilos
		#@mi_articulo = Article.find(params[:id])
	end

	def new

		#aqui instancio mi articulo nuevo vacio
		#para luego en la vista anadirle propiedades
		@nueva_moneda = Coin.new
		authorize! :create, @nueva_moneda
	end


	def create

		#Aqui finalmente creo mi articulo propiamente dicho
		#con los datos que mande de post de nuevo_articulo

		@nueva_moneda = Coin.new(coin_params)
		authorize! :create, @nueva_moneda

		#Aqui guardo finalmente mi articulo en mi tabla de la base de datos

		if @nueva_moneda.save
			redirect_to @nueva_moneda

		else
			render :new
		end


		#hago un redireccionamiento a mi la pagina de mi articulo
		
	end

	def delete
		@arreglo_de_monedas = Coin.all
	end

	def destroy
		@nueva_moneda.destroy
		redirect_to articles_path
	end

	def edit
	end

	def update
		if @nueva_moneda.update(article_params)
			redirect_to @nueva_moneda
		else
			render :edit
		end
	end

	#STRONG_PARAM

	private

	def coin_params
		params.require(:coin).permit(:nombre)
	end


	def set_coin
		@nueva_moneda = Coin.find(params[:id])
end
end

app/controllers/cp_controller.rb
class CpController < ApplicationController
	#Pagina principal para apostar
	load_and_authorize_resource
	def jugar
		hora
		@respuesta = nil;
		if request.post?
			@respuesta = false;
      		@info = {
      			:monto => params[:monto].to_f,
         		:moneda => params[:moneda]
         		};
  				if current_user.saldo >= @info[:monto]	
	  				@respuesta = true
	  				current_user.update(:saldo => current_user.saldo - @info[:monto])
			  		moneda = Coin.find_by(nombre: params[:moneda])
			  		@bet = Bet.new(:user => current_user, :coin => moneda, :cantidad => @info[:monto])
			  		@bet.save
			  	end
		end
	end

	#Pagina principal para recargar y ver saldo
	def saldo
		hora
		if request.post?

			@saldo1 ={
				:saldo => params[:saldo_a_enviar].to_f/100
				} 
			@usuario = current_user
			@saldo_actual = current_user.saldo
			@nuevo_saldo = @saldo_actual + @saldo1[:saldo]
			@usuario = current_user.update(:saldo => @nuevo_saldo)

		end

	end

	#Pagina para modificar y ver perfil
	def perfil
		hora
	end

	#Pagina con los resultados del dia
	def resultados
		hora
		@arreglo_de_resultados = Result.all
		@contador=0
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  load_and_authorize_resource
  def index
  	hora
  end

  #Pagina con info de la empresa
  def conocenos
  	hora
  end

  #Pagina sobre como jugar
  def aprende
  	hora
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cp_helper.rb
module CpHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<h3 class="text-center">Crea una nueva moneda y anadela a la BD</h3>

<%=form_for(@nueva_moneda) do |f| %>
<div class="formularioMoneda">
<%= f.text_field :nombre, placeholder: "Ingresa el nombre de la moneda", class:"form-control nombreMoneda" %>

<%= f.label :Imagen %>
  <%= f.file_field :image %>

<%= f.submit "Crear Moneda", class:"btn tableroMonedas white"%>
<%end%>
</div>

app/views/coins/delete.html.erb
<table class="rwd-table">
  <tr>
    <th>Moneda</th>
    <th>Imagen</th>
    <th>Opcion</th>

  </tr>

<%=@arreglo_de_monedas.each do |iterador|%> 

	<tr>
    <td data-th="Moneda"><%=iterador.nombre%></td>
    <td data-th="Imagen"><%=image_tag "#{iterador.nombre}.png" , :class => "imagenCrypto2"%>
    <td data-th="Opcion">Borrar</td>
</td>
  </tr>

<%end%>	
</table>
	

app/views/coins/edit.html.erb
<%= render "form", name: "editar"%>

app/views/coins/index.html.erb
<div class="espacioListaMonedas">
	

<% @arreglo_de_monedas.each do |iterador_moneda| %>
<div class="listaMonedas">
<p>Moneda: <%= iterador_moneda.nombre %></p>
<%=image_tag "#{iterador_moneda.nombre}.png", :class => "imagenCrypto2"%>
</div>
<%end%>
</div>

app/views/coins/new.html.erb
<%= render  "form", name: "crear"%>

app/views/coins/show.html.erb
<h1> Este es mi moneda </h1> 

<h2><%= @nueva_moneda.nombre %></h2>

app/views/cp/jugar.html.erb
<div id="templatemo_wrapper">
<h1>¡Que comiencen las apuestas!</h1>


<h2> Apuesta </h2>
<%= form_tag({:controller => "cp", :action => "jugar"}, :method => "post") do %>

   <div class="tableroMonedas">
      
      <%= image_tag "aeternity.png", :class => "imagenCrypto", :alt => "aeternity"%>
      <%= image_tag "ardor.png", :class => "imagenCrypto", :alt => "ardor"%>
      <%= image_tag "ark.png", :class => "imagenCrypto", :alt => "ark"%>
      <%= image_tag "binancecoin.png", :class => "imagenCrypto", :alt => "binancecoin"%>
      <%= image_tag "bitconnect.png", :class => "imagenCrypto", :alt => "bitconnect"%>
      <%= image_tag "bitcoin.png", :class => "imagenCrypto", :alt => "bitcoin"%>
      <%= image_tag "bitshares.png", :class => "imagenCrypto", :alt => "bitshares"%>
      <%= image_tag "bytecoin.png", :class => "imagenCrypto", :alt => "bytecoin"%>
      <%= image_tag "bytom.png", :class => "imagenCrypto", :alt => "bytom"%>
      <%= image_tag "cardano.png", :class => "imagenCrypto", :alt => "cardano"%>
      <%= image_tag "dash.png", :class => "imagenCrypto", :alt => "dash"%>
      <%= image_tag "decred.png", :class => "imagenCrypto", :alt => "decred"%>
      <%= image_tag "eos.png", :class => "imagenCrypto", :alt => "eos"%>
      <%= image_tag "ethereum.png", :class => "imagenCrypto", :alt => "ethereum"%>
      <%= image_tag "factom.png", :class => "imagenCrypto", :alt => "factom"%>
      <%= image_tag "golem.png", :class => "imagenCrypto", :alt => "golem"%>
      <%= image_tag "hshare.png", :class => "imagenCrypto", :alt => "hshare"%>
      <%= image_tag "iconomi.png", :class => "imagenCrypto", :alt => "iconomi"%>
      <%= image_tag "komodo.png", :class => "imagenCrypto", :alt => "komodo"%>
      <%= image_tag "lisk.png", :class => "imagenCrypto", :alt => "lisk"%>
      <%= image_tag "litecoin.png", :class => "imagenCrypto", :alt => "litecoin"%>
      <%= image_tag "maidsafecoin.png", :class => "imagenCrypto", :alt => "maidsafecoin"%>
      <%= image_tag "miota.png", :class => "imagenCrypto", :alt => "miota"%>
      <%= image_tag "monero.png", :class => "imagenCrypto", :alt => "monero"%>
      <%= image_tag "nem.png", :class => "imagenCrypto", :alt => "nem"%>
      <%= image_tag "neo.png", :class => "imagenCrypto", :alt => "neo"%>
      <%= image_tag "pivx.png", :class => "imagenCrypto", :alt => "pivx"%>
      <%= image_tag "qtum.png", :class => "imagenCrypto", :alt => "qtum"%>
      <%= image_tag "ripple.png", :class => "imagenCrypto", :alt => "ripple"%>
      <%= image_tag "siacoin.png", :class => "imagenCrypto", :alt => "siacoin"%>
      <%= image_tag "steem.png", :class => "imagenCrypto", :alt => "steem"%>
      <%= image_tag "stellar.png", :class => "imagenCrypto", :alt => "stellar"%>
      <%= image_tag "stratis.png", :class => "imagenCrypto", :alt => "stratis"%>
      <%= image_tag "tether.png", :class => "imagenCrypto", :alt => "tether"%>
      <%= image_tag "vertcoin.png", :class => "imagenCrypto", :alt => "vertcoin"%>
      <%= image_tag "waves.png", :class => "imagenCrypto", :alt => "waves"%>




   </div>
   <div id="formularioJugar">
   <%= label_tag "monto", "Monto" %>
   <br />
   <%= number_field_tag  "monto", "", :required => "required", min: 0.0000000001, step: :any %>
   <br />
   <%= @campo = hidden_field "moneda", "", :required => "required", :id =>"campoMoneda"%>

   <br />
   <%= submit_tag "Apostar" %>
<% end %>

<% if request.post?%>
   <% if @respuesta %>
      <p> Gracias por publicar tu apuesta </p>

   <% elsif @seleccion_nula %>
      <p>No seleccionaste ninguna moneda</p> 
   <% else %>
      <p>Tienes menos saldo de lo que quieres apostar!</p>
   <%end%>  
<%end%>
<div>
   
</div>
</div>
</div>

app/views/cp/perfil.html.erb
<h1>pagina de perfil de user</h1>

app/views/cp/resultados.html.erb
<div id="templatemo_wrapper">
<h1>Pagina de resultados del dia</h1>

<table class="rwd-table">
  <tr>
    <th>#</th>
    <th>Hora</th>
    <th>Moneda</th>
    <th>Imagen</th>

  </tr>

<% @arreglo_de_resultados.each_with_index  do |iterador,i|%>

	<tr>
    <td data-th="#"><%=i+1%></td>
    <td data-th="Hora"><%=iterador.fecha%></td>
    <td data-th="Moneda"><%=iterador.coin.nombre%></td>
    <td data-th="Imagen"><%=image_tag "#{iterador.coin.nombre}.png" , :class => "imagenCrypto2"%></td>
  </tr>

<%end%>	
</table>
</div>

app/views/cp/saldo.html.erb
<div id="templatemo_wrapper">

<div class="section-recargar">
<div class="tarjeta">
 <form>
 	<h1>Recargar Saldo</h1>
  <input type="radio" name="tdc" value="Visa" checked> Visa
  <input type="radio" name="tdc" value="Mastercard" checked> Mastercard<br><br>
  Numero de cuenta: <br>
  <input type="text" name="numerocuenta" class="form-control"><br>
  Codigo de Seguridad:<br>
  <input type="text" name="codigoseguridad" class="form-control"><br>
  Fecha de vencimiento<br>
  <span>
     <select name="mes">
        <option value="January">Enero</option>
        <option value="February">Febrero</option>
        <option value="March">Marzo</option>
        <option value="April">Abril</option>
        <option value="May">Mayo</option>
        <option value="June">Junio</option>
        <option value="July">Julio</option>
        <option value="August">Agosto</option>
        <option value="September">Septiembre</option>
        <option value="October">Octubre</option>
        <option value="November">Noviembre</option>
        <option value="December">Diciembre</option>
     </select> 
</span>
<span>
     <select name="day">
          <option value="2014">2014</option>
          <option value="2013">2013</option>
          <option value="2012">2012</option>
          <option value="2011">2011</option>
          <option value="2010">2010</option>
          <option value="2009">2009</option>
          <option value="2008">2008</option>
          <option value="2007">2007</option>
          <option value="2006">2006</option>
          <option value="2005">2005</option>
          <option value="2004">2004</option>
          <option value="2003">2003</option>
          <option value="2002">2002</option>
          <option value="2001">2001</option>
          <option value="2000">2000</option>
          <option value="1999">1999</option>
          <option value="1998">1998</option>
          <option value="1997">1997</option>
          <option value="1996">1996</option>
          <option value="1995">1995</option>
          <option value="1994">1994</option>
          <option value="1993">1993</option>
          <option value="1992">1992</option>
          <option value="1991">1991</option>
          <option value="1990">1990</option>
          <option value="1989">1989</option>
          <option value="1988">1988</option>
          <option value="1987">1987</option>
          <option value="1986">1986</option>
          <option value="1985">1985</option>
          <option value="1984">1984</option>
          <option value="1983">1983</option>
          <option value="1982">1982</option>
          <option value="1981">1981</option>
          <option value="1980">1980</option>
          <option value="1979">1979</option>
          <option value="1978">1978</option>
          <option value="1977">1977</option>
          <option value="1976">1976</option>
          <option value="1975">1975</option>
          <option value="1974">1974</option>
          <option value="1973">1973</option>
          <option value="1972">1972</option>
          <option value="1971">1971</option>
          <option value="1970">1970</option>
          <option value="1969">1969</option>
          <option value="1968">1968</option>
          <option value="1967">1967</option>
          <option value="1966">1966</option>
          <option value="1965">1965</option>
		  <option value="1964">1964</option>
	</select>
</span>
<br> Cedula de identidad <br>
<input type="text" name="Cedula de identidad" class="form-control"><br>
</form> 
<div id="coindesk-widget" ></div>
	<script type="text/javascript" src="//widget.coindesk.com/bpiticker/coindesk-widget.min.js"></script>

</div>

<div class="seccionRecargar">
<h2> Monto a cambiar</h2>
   <br />

   <%= form_tag({:controller => "cp", :action => "saldo"}, :method => "post") do %>
   <%= label_tag "saldo", "monto en bsf " %>

   <%= number_field_tag  "saldo_a_enviar", "", :required => "required", min: 0.0000000001, step: :any, :class => "form-control campoRecargar" %>
  

   
   <%= submit_tag "Recargar", :class => "btn tableroMonedas white"%>
<% end %>
  <p>Tu saldo actual es de: <%=current_user.saldo%> </p>
<% if @saldo1 %>
   <p> <strong><%= @saldo1[:saldo] %></strong> fue lo que recargaste</p>
   
<% end %>
</div>
</div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CriptoPlay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "partials/navigation" %>

<!-- Las notificaciones de usuario     -->
 <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>
<%= render "partials/footer" %>

</body>
</html>

app/views/partials/_footer.html.erb
<footer>

		<div class="redesSociales roboto">
			<p> Siguenos en:   </p>
			<a href=""><i class="icon-instagram"></i></a>
			<a href=""><i class="icon-twitter"></i></a>
			<a href=""><i class="icon-tumblr"></i></a>
			<a href=""><i class="icon-facebook"></i></a>
			<a href=""><i class="icon-github"></i></a>
		</div>
		<div class="columna roboto">
			<h6>KDMJ Team</h6>
			<ul>
				<li><a href="">Empresa</a></li>
				<li><a href="">Blog</a></li>
				<li><a href="">Declaracion de privacidad</a></li>
				<li><a href="">Terminos del servicio</a></li>
			</ul>
		</div>
		<div class="columna roboto">
			<h6>Asistencia tecnica</h6>
			<ul>
				<li><a href="">Centro de ayuda</a></li>
				<li><a href="">Manual de usuario</a></li>
				<li><a href="">Seguridad</a></li>
			</ul>
		</div>
		<div class="columna roboto">
			<h6>Contacto</h6>
			<ul>
				<li><a href="">Contacto</a></li>
				<li><a href="">Manual de usuario</a></li>
				<li><a href="">Seguridad</a></li>
			</ul>
		</div>
	<div class="copyRight">
		<p>© 2017 KDMJ Team, Inc. KDMJ Team es una marca registrada de KMDJ, Inc.</p>
	</div>
	</footer>

app/views/partials/_navigation.html.erb
<script type="text/javascript">
      var flashvars = {};
      flashvars.cssSource = "css/piecemaker.css";
      flashvars.xmlSource = "piecemaker.xml";
		
      var params = {};
      params.play = "true";
      params.menu = "false";
      params.scale = "showall";
      params.wmode = "transparent";
      params.allowfullscreen = "true";
      params.allowscriptaccess = "always";
      params.allownetworking = "all";
	  
      swfobject.embedSWF('piecemaker.swf', 'piecemaker', '960', '500', '10', null, flashvars,    
      params, null);
    
    </script>

<script type="text/javascript">

ddsmoothmenu.init({
	mainmenuid: "templatemo_menu", //menu DIV id
	orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
	classname: 'ddsmoothmenu', //class added to menu's outer DIV
	//customtheme: ["#1c5a80", "#18374a"],
	contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
})

</script>

<header>
<div id="templatemo_wrapper">
<div id="templatemo_header">
    
    	<div id="site_title"><h1><%= link_to "", root_path %></h1></div>
        
        <div id="templatemo_menu" class="ddsmoothmenu">
            <ul>
              	<li><%= link_to "Inicio", root_path %></li>
          		<li><%= link_to "Conocenos",  welcome_conocenos_path  %></li>
          		<li><%= link_to "Resultado", cp_resultados_path %></li>
              	<%if user_signed_in? %>

              	<li><%= link_to "Saldo:#{current_user.saldo}",  cp_saldo_path %></li>
                <li><%= link_to "Jugar",cp_jugar_path, :method => 'get' %>
                	<ul>
                		<li><%= link_to "Como jugar",cp_jugar_path, :method => 'get' %></li>
                	</ul>
                </li>
                <li><a href="">Cuenta</a>
                	<ul>
                		<li><%= link_to "Recargar Saldo",  cp_saldo_path %></li>
                        <li><%= link_to "Cerrar sesion",  destroy_user_session_path, method: :delete, class: "itemMenu" %> </li>
                        

                  	</ul>
                </li>

                <%else%>

                

              	<li><a href="">Entrar</a>
                	<ul>
                        <li><%= link_to "Iniciar sesion", new_user_session_path, class: "itemMenu"%></li>
                        <li><%= link_to "Crear cuenta", new_user_registration_path,class: "itemMenu" %></li>

                  	</ul>
                </li>
                <%end%>
            </ul>
            <br style="clear: left" />
        </div> <!-- end of templatemo_menu -->
        
</div> <!-- end of header -->
</div>
</header>


<% if can? :create, Coin %>

<div>
	<nav class="menuAdmin d-flex justify-content-around">
		<h3 class="tituloPanelAdmin">Panel Administrador</h3>
		<ul class="d-flex listaAdmin">
			<li class="mr-3 elementoListaAdmin"><%=link_to "Crear Moneda", '/coins/new'%></li>
			<li class="mr-3 elementoListaAdmin"><%=link_to "Eliminar", '/coins/delete'%></li>
			<li class="mr-3 elementoListaAdmin">Eliminar Usuario</li>

		</ul>
	</nav>
</div>
<%end%>

app/views/welcome/aprende.html.erb
<h1>Pagina aprende funcionando y linkeando</h1>

app/views/welcome/conocenos.html.erb
<div id="templatemo_main centrar">
    	<h2 class="tituloprincipal">Equipo</h2>
        <%=image_tag "equipo.jpg" , :alt => "equipo", :id => "equipo"%>
        <p class="textoEquipo">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <div class="espacioEquipo">

            <div class="miembro">

            	<%= image_tag "jbasanta.png", :alt => "tamanoMiembro", :class => "tamanoMiembro" %>
                <p class="tituloprincipal">Jose Basanta.
                <p>Estudiante de Ing computacion</p>
                <p>Diseñador Frontend</p>
                <p>Desarrollador Backend</p>
            </div>
            <div class="miembro">
            	<%= image_tag "jkauze.png", :alt => "tamanoMiembro", :class => "tamanoMiembro" %>
                <p class="tituloprincipal">Jesus Kauze</p> 
                <p>Estudiante de Ing computacion</p>
                <p>Administrador de sistemas</p>
                <p>Desarrollador Backend</p>
            </div>
            <div class="miembro">
            	<%= image_tag "mrodriguez.png", :alt => "tamanoMiembro", :class => "tamanoMiembro" %>
                <p class="tituloprincipal">Manuel Rodriguez</p> 
                <p>Estudiante de Ing computacion</p>
                <p>Experto de git</p>
                <p>Desarrollador Backend</p>
            </div>
            <div class="miembro">
            	            	<%= image_tag "dsegura.png", :alt => "tamanoMiembro", :class => "tamanoMiembro" %>
                <p class="tituloprincipal">David Segura</p>  
                <p>Estudiante Ing Computacion</p>
                <p>Diseñador Gráfico</p>
                <p>Desarrollador Frontend</p>
            </div>
            

        </div>

app/views/welcome/index.html.erb
<div class="socialBar">
    <ul>
      <li><a href=""  target="_blank"  class="icon-facebook"></a></li>
      <li><a href="" target="_blank"  class="icon-twitter"></a></li>
      <li><a href=""  target="_blank" class="icon-instagram"></a></li>
    </ul>
</div>

<div id="templatemo_wrapper">
    <div id="templatemo_fw">
        
            <!-- Carousel items -->

          <h2 class="titulo">Comienza a jugar ahora mismo!</h2>

          <div class="mainSlides">
            <div class="slides">
              <div class="espacioImagen1">
                <p>Apuesta diariamente a una de las 36 CriptoMonedas e intenta ganar</p>
              </div>
            
              <div class="espacioImagen2">
                <p>Sistema basado en las criptomonedas</p>
              </div>

              <div class="espacioImagen3">
                <p>Parque Cristal</p>
              </div>
            </div>
        </div>

	</div>
    
    <div id="templatemo_main">
    	<div class="col_fw">
        	<div class="col_w460 float_l">
            	<h2 class="titulo2">Reglas del Juego</h2>
                <div class="cleaner h20"></div>
                <ul class="tmo_list margen">
                  <li>CriptoPlay es un juego de ENVITE Y AZAR, que consiste en la extracción aleatoria de UNA (1) CRIPTOMONEDA que resultará ganadora en cada uno de los sorteos establecidos. Permitiendo escoger entre 36 criptomonedas y pagándose 29 veces el monto de la apuesta.</li>
                  <li>La(s) apuesta(s) de los jugadores se harán a través de la sección Jugar.</li>
                  <li>La jugada mínima y máxima no tiene restricción.</li>
                  <li>El jugador debe ser mayor de edad.</li>
                  <li>Las jugadas se realizarán hasta 5 minutos antes de cada sorteo. Jugadas realizadas por encima de ese horario se considerará como jugadas no válidas retornando de forma automática el monto de la jugada.</li>
                  <li>El jugador ganador se le abonará el premio en la cartera asignada.</li>
                  <li>El pago de los premios es responsabilidad exclusiva del administrador de CriptoPlay.</li>
                </ul>
                <div class="cleaner h20"></div>
                <a href="#" class="more float_r"></a>
            </div>
            <div class="col_w460 float_r">
            	<h2 class="titulo2">Monedas</h2>
            	<%= image_tag "monedasindex.png", :alt => "image 02" ,:class =>"imagenesmonedas" %>

            </div>
            <div class="cleaner"></div>
		</div>
    </div>
    
    <div class="cleaner"></div>

</div> 

<script type="text/javascript" src="../assets/jquery.min.js"></script>
<script src="../assets/jquery.slides.js"></script>


<script type="text/javascript">
    $(function(){
      $(".slides").slidesjs({
          play: {
              active: true,
              // [boolean] Generate the play and stop buttons.
              // You cannot use your own buttons. Sorry.
              effect: "slide",
              // [string] Can be either "slide" or "fade".
              interval: 3000,
              // [number] Time spent on each slide in milliseconds.
              auto: true,
              // [boolean] Start playing the slideshow on load.
              swap: true,
              // [boolean] show/hide stop and play buttons
              pauseOnHover: false,
              // [boolean] pause a playing slideshow on hover
              restartDelay: 2500
              // [number] restart delay on inactive slideshow
          }
        });
    });
</script>